作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
ary1 = np.arange(0, 20+1, 1)
ary1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
#2.呈上題，將以上數列取出偶數。
ary2 = np.array([x for x in ary1 if x % 2 == 0])
ary2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
#3.呈1題，將數列取出3的倍數。
ary3 = np.array([x for x in ary1 if x % 3 == 0])
ary3

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
print(ary1.ndim, ary1.shape)
print(ary2.ndim, ary2.shape)
print(ary3.ndim, ary3.shape)

1 (21,)
1 (11,)
1 (7,)


In [15]:
np.ones([2, 3, 4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])