In [1]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [3]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

print(array1)

print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [4]:
with open('day06_multi_array.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2)

In [5]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

npzfile = np.load('day06_multi_array.npz')

print(type(npzfile))

print(npzfile.files)

print(npzfile["array1"])

print(npzfile["array2"])

<class 'numpy.lib.npyio.NpzFile'>
['array1', 'array2']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [6]:
array3 = np.array(range(20))

with open('day06_multi_array2.npz', 'wb') as f:
    np.savez(f, array1=npzfile["array1"], array2=npzfile["array2"], array3=array3)

npzfile2 = np.load('day06_multi_array2.npz')

print(npzfile2.files)

print(npzfile2["array1"])

print(npzfile2["array2"])

print(npzfile2["array3"])

['array1', 'array2', 'array3']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
