作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [3]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([
                    [10, 8]
                    , [3, 5]
                    ])

print(array1)

[[10  8]
 [ 3  5]]


In [4]:
ary1_inv = np.linalg.inv(array1)

print(ary1_inv)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


In [5]:
ary1_mat = array1 @ ary1_inv

print(ary1_mat)

[[1. 0.]
 [0. 1.]]


In [6]:
#2. 運用上列array計算特徵值、特徵向量?

w, v = np.linalg.eig(array1)

print(w)

print(v)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [7]:
#3. 運用上列array計算SVD?

u, s, vh = np.linalg.svd(array1)

print(u)

print(s)

print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
